In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/Users/prachisharma/Desktop/Churn Analysis Project/ravenstack_accounts.csv')
df

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True
...,...,...,...,...,...,...,...,...,...,...
495,A-8ae3fc,Company_495,DevTools,CA,2024-06-28,ads,Pro,9,False,False
496,A-55f257,Company_496,FinTech,US,2023-12-21,organic,Basic,9,False,False
497,A-d26ab4,Company_497,DevTools,UK,2024-11-07,organic,Basic,9,False,True
498,A-712533,Company_498,EdTech,US,2023-07-31,organic,Pro,18,False,False
499,A-781cc0,Company_499,EdTech,US,2024-09-04,organic,Pro,12,False,False

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    str
 1   account_name     500 non-null    str
 2   industry         500 non-null    str
 3   country          500 non-null    str
 4   signup_date      500 non-null    str
 5   referral_source  500 non-null    str
 6   plan_tier        500 non-null    str
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), str(7)
memory usage: 32.4 KB

In [4]:
df.describe()

            seats
count  500.000000
mean    20.560000
std     21.044718
min      1.000000
25%      5.000000
50%     15.000000
75%     28.000000
max    163.000000

In [6]:
df.isnull().sum()

account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

In [10]:
df[df.duplicated()].shape

(0, 10)

Changing the Format

In [16]:
df['signup_date'] = pd.to_datetime(df['signup_date'])

In [ ]:

df['account_tenure_days'] = (pd.Timestamp.today() - df['signup_date']).dt.days

#obtained the signup days

In [18]:
df['industry'] = df['industry'].str.strip().str.lower()
df['country'] = df['country'].str.strip().str.upper() 
df['plan_tier'] = df['plan_tier'].str.strip().str.title()
df['referral_source'] = df['referral_source'].str.strip().str.lower()

CHANGING THE DATA TYPE

In [19]:
df['is_trial'] = df['is_trial'].astype(int)
df['churn_flag'] = df['churn_flag'].astype(int)

In [23]:
# Verification of changed data types

print(df.dtypes)
print(df.head(3))

account_id                        str
account_name                      str
industry                          str
country                           str
signup_date            datetime64[us]
referral_source                   str
plan_tier                         str
seats                           int64
is_trial                        int64
churn_flag                      int64
account_tenure_days             int64
dtype: object
  account_id account_name  industry country signup_date referral_source  \
0   A-2e4581    Company_0    edtech      US  2024-10-16         partner
1   A-43a9e3    Company_1   fintech      IN  2023-08-17           other
2   A-0a282f    Company_2  devtools      US  2024-08-27         organic

  plan_tier  seats  is_trial  churn_flag  account_tenure_days
0     Basic      9         0           0                  575
1     Basic     18         0           1                 1001
2     Basic      1         0           0                  625

In [24]:
df.to_csv('ravenstack_accounts_cleaned.csv', index=False)

Now the procedure to be run for the other 4 files too.

In [3]:
import pandas as pd

df_churn = pd.read_csv('/Users/prachisharma/Desktop/Churn Analysis Project/ravenstack_churn_events.csv')
df_churn.head(5)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive

In [26]:
df_churn.describe()

       refund_amount_usd
count         600.000000
mean           14.420417
std            39.224591
min             0.000000
25%             0.000000
50%             0.000000
75%             0.000000
max           392.920000

In [27]:
df_churn.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    str
 1   account_id                600 non-null    str
 2   churn_date                600 non-null    str
 3   reason_code               600 non-null    str
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    str
dtypes: bool(3), float64(1), str(5)
memory usage: 30.0 KB

In [28]:
#changing the data type of churn date

df_churn['churn_date'] = pd.to_datetime(df_churn['churn_date'])

In [4]:
#lowercasing the reason code column

df_churn['reason_code'] = df_churn['reason_code'].str.strip().str.lower()

In [ ]:
#filling no feedback texts

df_churn['feedback_text'] = df_churn['feedback_text'].fillna('no feedback')

In [ ]:
#conveeting the boolean values to o/1

df_churn['preceding_upgrade_flag'] = df_churn['preceding_upgrade_flag'].astype(int)
df_churn['preceding_downgrade_flag'] = df_churn['preceding_downgrade_flag'].astype(int)
df_churn['is_reactivation'] = df_churn['is_reactivation'].astype(int)

In [5]:
#saving as cleaned file

df_churn.to_csv('cleaned-churn_events.csv', index= False)

In [ ]:
df_churn.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    str
 1   account_id                600 non-null    str
 2   churn_date                600 non-null    datetime64[us]
 3   reason_code               600 non-null    object
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    int64
 6   preceding_downgrade_flag  600 non-null    int64
 7   is_reactivation           600 non-null    int64
 8   feedback_text             600 non-null    str
dtypes: datetime64[us](1), float64(1), int64(3), object(1), str(3)
memory usage: 42.3+ KB

In [ ]:
df_churn.isnull().sum()

churn_event_id              0
account_id                  0
churn_date                  0
reason_code                 0
refund_amount_usd           0
preceding_upgrade_flag      0
preceding_downgrade_flag    0
is_reactivation             0
feedback_text               0
dtype: int64

In [ ]:
import pandas as pd

df_usage = pd.read_csv('/Users/prachisharma/Desktop/Churn Analysis Project/ravenstack_feature_usage.csv')

In [ ]:
df_usage.head(10)

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False
5,U-c5692d,S-e958ba,2023-10-31,feature_14,11,4103,0,False
6,U-7078db,S-0c9fdd,2023-09-20,feature_34,8,2016,2,False
7,U-a60033,S-4e4ab7,2023-06-05,feature_27,10,5470,0,False
8,U-5cd930,S-a3a1c1,2024-02-20,feature_18,9,5067,1,False
9,U-ebb375,S-9e450b,2023-02-09,feature_28,6,2778,0,False

In [ ]:
df_usage[df_usage['usage_count']== 0]

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
2875,U-a72131,S-9925b9,2023-08-01,feature_25,0,0,0,False
3327,U-370ae6,S-c98905,2023-03-15,feature_34,0,0,2,True

In [ ]:
df_usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             25000 non-null  str
 1   subscription_id      25000 non-null  str
 2   usage_date           25000 non-null  str
 3   feature_name         25000 non-null  str
 4   usage_count          25000 non-null  int64
 5   usage_duration_secs  25000 non-null  int64
 6   error_count          25000 non-null  int64
 7   is_beta_feature      25000 non-null  bool
dtypes: bool(1), int64(3), str(4)
memory usage: 1.4 MB

In [ ]:
# converting the usage date column to date time

df_usage['usage_date'] = pd.to_datetime(df_usage['usage_date'])

In [ ]:
df_usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             25000 non-null  str
 1   subscription_id      25000 non-null  str
 2   usage_date           25000 non-null  datetime64[us]
 3   feature_name         25000 non-null  str
 4   usage_count          25000 non-null  int64
 5   usage_duration_secs  25000 non-null  int64
 6   error_count          25000 non-null  int64
 7   is_beta_feature      25000 non-null  bool
dtypes: bool(1), datetime64[us](1), int64(3), str(3)
memory usage: 1.4 MB

In [ ]:
df_usage['feature_name'] = df_usage['feature_name'].str.strip().str.lower()

In [ ]:
df_usage['usage_duration_mins'] = (df_usage['usage_duration_secs'] / 60).round(2)

In [ ]:
df_usage['is_zero_usage'] = (df_usage['usage_count'] == 0).astype(int)

In [ ]:
df_usage['is_beta_feature'] = df_usage['is_beta_feature'].astype(int)

In [ ]:
df_usage.to_csv('ravenstack_feature_usage_cleaned.csv', index=False)

print(df_usage.dtypes)
print(df_usage.isnull().sum())

usage_id                          str
subscription_id                   str
usage_date             datetime64[us]
feature_name                      str
usage_count                     int64
usage_duration_secs             int64
error_count                     int64
is_beta_feature                 int64
usage_duration_mins           float64
is_zero_usage                   int64
dtype: object
usage_id               0
subscription_id        0
usage_date             0
feature_name           0
usage_count            0
usage_duration_secs    0
error_count            0
is_beta_feature        0
usage_duration_mins    0
is_zero_usage          0
dtype: int64

In [7]:
#Importing new file

import pandas as pd

df_subs = pd.read_csv('/Users/prachisharma/Desktop/Churn Analysis Project/ravenstack_subscriptions.csv')
df_subs.head(10)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,Pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaN,Enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaN,Enterprise,27,5373,64476,False,False,False,False,monthly,True
5,S-4b9b13,A-fa2041,2024-08-13,NaN,Pro,15,735,8820,False,False,False,False,monthly,True
6,S-dceac6,A-417d2f,2023-12-30,NaN,Enterprise,4,796,9552,False,False,False,False,annual,True
7,S-8cad7b,A-5f2961,2024-12-23,NaN,Basic,16,304,3648,False,False,False,False,annual,True
8,S-24796e,A-cc8c8f,2024-11-27,NaN,Enterprise,23,4577,54924,False,False,False,False,annual,False
9,S-d0c344,A-80eeb6,2024-10-27,NaN,Pro,22,1078,12936,False,False,False,False,annual,False

In [ ]:
df_subs.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    5000 non-null   str
 1   account_id         5000 non-null   str
 2   start_date         5000 non-null   str
 3   end_date           486 non-null    str
 4   plan_tier          5000 non-null   str
 5   seats              5000 non-null   int64
 6   mrr_amount         5000 non-null   int64
 7   arr_amount         5000 non-null   int64
 8   is_trial           5000 non-null   bool
 9   upgrade_flag       5000 non-null   bool
 10  downgrade_flag     5000 non-null   bool
 11  churn_flag         5000 non-null   bool
 12  billing_frequency  5000 non-null   str
 13  auto_renew_flag    5000 non-null   bool
dtypes: bool(5), int64(3), str(6)
memory usage: 376.1 KB

In [ ]:
df_subs['start_date'] = pd.to_datetime(df_subs['start_date'])
df_subs['end_date'] = pd.to_datetime(df_subs['end_date'])

In [ ]:
df_subs.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    5000 non-null   str
 1   account_id         5000 non-null   str
 2   start_date         5000 non-null   datetime64[us]
 3   end_date           486 non-null    datetime64[us]
 4   plan_tier          5000 non-null   str
 5   seats              5000 non-null   int64
 6   mrr_amount         5000 non-null   int64
 7   arr_amount         5000 non-null   int64
 8   is_trial           5000 non-null   bool
 9   upgrade_flag       5000 non-null   bool
 10  downgrade_flag     5000 non-null   bool
 11  churn_flag         5000 non-null   bool
 12  billing_frequency  5000 non-null   str
 13  auto_renew_flag    5000 non-null   bool
dtypes: bool(5), datetime64[us](2), int64(3), str(4)
memory usage: 376.1 KB

In [8]:
# df_subs['plan_tier'] = df_subs['plan_tier'].str.strip().str.lower()
df_subs['plan_tier'] = df_subs['plan_tier'].fillna('unknown').str.strip().str.lower()

In [ ]:
#Coverting the boolean values to int

df_subs['is_trial'] = df_subs['is_trial'].astype(int)
df_subs['upgrade_flag'] = df_subs['upgrade_flag'].astype(int)
df_subs['downgrade_flag'] = df_subs['downgrade_flag'].astype(int)
df_subs['churn_flag'] = df_subs['churn_flag'].astype(int)

In [ ]:
df_subs['auto_renew_flag'] = df_subs['auto_renew_flag'].astype(int)

In [ ]:
df_subs[df_subs['end_date'].isnull()]

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
1,S-0f6f44,A-9b9fe9,2024-06-11,NaT,<bound method StringMethods.lower of <pandas.c...,17,833,9996,0,0,0,0,monthly,1
2,S-51c0d1,A-659280,2024-11-25,NaT,<bound method StringMethods.lower of <pandas.c...,62,0,0,1,1,0,0,annual,0
4,S-cff5a2,A-ba6516,2024-01-10,NaT,<bound method StringMethods.lower of <pandas.c...,27,5373,64476,0,0,0,0,monthly,1
5,S-4b9b13,A-fa2041,2024-08-13,NaT,<bound method StringMethods.lower of <pandas.c...,15,735,8820,0,0,0,0,monthly,1
6,S-dceac6,A-417d2f,2023-12-30,NaT,<bound method StringMethods.lower of <pandas.c...,4,796,9552,0,0,0,0,annual,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S-c158df,A-fa2041,2024-10-27,NaT,<bound method StringMethods.lower of <pandas.c...,18,3582,42984,0,0,0,0,monthly,1
4996,S-b49c0a,A-db5e9e,2024-12-05,NaT,<bound method StringMethods.lower of <pandas.c...,23,1127,13524,0,0,0,0,monthly,0
4997,S-42822d,A-443f6f,2024-12-15,NaT,<bound method StringMethods.lower of <pandas.c...,25,1225,14700,0,0,0,0,annual,1
4998,S-432401,A-c7ffc2,2023-05-25,NaT,<bound method StringMethods.lower of <pandas.c...,132,6468,77616,0,0,0,0,monthly,1
4999,S-71fc3d,A-ccb686,2024-12-06,NaT,<bound method StringMethods.lower of <pandas.c...,10,1990,23880,0,0,0,0,monthly,1

In [ ]:
df_subs['end_date'] = df_subs['end_date'].fillna(pd.Timestamp.today().strftime('%Y-%m-%d'))

In [ ]:
df_subs['subscription_duration_days'] = (
    df_subs['end_date'] - df_subs['start_date']
).dt.days

In [9]:
df_subs.to_csv('ravenstack_subscriptions_cleaned.csv', index=False)

In [ ]:
import pandas as pd

df_tickets = pd.read_csv('/Users/prachisharma/Desktop/Churn Analysis Project/ravenstack_support_tickets.csv')

df_tickets.head(10)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,False
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,False
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,False
5,T-90f06d,A-94c3cd,2023-07-27,2023-07-27 09:00:00,9.0,medium,60,NaN,False
6,T-30b537,A-2e4581,2023-09-09,2023-09-10 03:00:00,27.0,urgent,64,3.0,False
7,T-60242d,A-72799b,2024-01-29,2024-01-29 12:00:00,12.0,low,56,4.0,True
8,T-7119c9,A-b179bf,2023-08-27,2023-08-27 16:00:00,16.0,urgent,154,NaN,False
9,T-b0edf2,A-7cfe77,2024-05-06,2024-05-07 04:00:00,28.0,medium,150,3.0,False

In [ ]:
df_tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ticket_id                    2000 non-null   str
 1   account_id                   2000 non-null   str
 2   submitted_at                 2000 non-null   str
 3   closed_at                    2000 non-null   str
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   str
 6   first_response_time_minutes  2000 non-null   int64
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   bool
dtypes: bool(1), float64(2), int64(1), str(5)
memory usage: 127.1 KB

In [ ]:
df_tickets['submitted_at'] = pd.to_datetime(df_tickets['submitted_at'])
df_tickets['closed_at'] = pd.to_datetime(df_tickets['closed_at'])

In [ ]:
df_tickets['priority'] = df_tickets['priority'].str.strip().str.lower()

In [ ]:
df_tickets['escalation_flag'] = df_tickets['escalation_flag'].astype(int)

In [ ]:
df_tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ticket_id                    2000 non-null   str
 1   account_id                   2000 non-null   str
 2   submitted_at                 2000 non-null   datetime64[us]
 3   closed_at                    2000 non-null   datetime64[us]
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   str
 6   first_response_time_minutes  2000 non-null   int64
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   int64
dtypes: datetime64[us](2), float64(2), int64(2), str(3)
memory usage: 140.8 KB

In [ ]:
df_tickets[df_tickets['satisfaction_score'].isnull()]

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,0
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,0
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,0
5,T-90f06d,A-94c3cd,2023-07-27,2023-07-27 09:00:00,9.0,medium,60,NaN,0
8,T-7119c9,A-b179bf,2023-08-27,2023-08-27 16:00:00,16.0,urgent,154,NaN,0
...,...,...,...,...,...,...,...,...,...
1991,T-a35ae1,A-80eeb6,2023-01-30,2023-02-01 20:00:00,68.0,high,38,NaN,0
1992,T-ffdef9,A-1b707d,2023-09-17,2023-09-18 21:00:00,45.0,low,13,NaN,0
1993,T-76632d,A-00bed1,2024-05-16,2024-05-17 03:00:00,27.0,high,46,NaN,0
1995,T-d9d697,A-417d2f,2024-11-06,2024-11-08 22:00:00,70.0,urgent,3,NaN,0
1999,T-ccf229,A-b2225d,2024-07-10,2024-07-12 12:00:00,60.0,high,24,NaN,0

In [ ]:
# fill median score to the missing values

median_score = df_tickets['satisfaction_score'].median()
df_tickets['satisfaction_score'] = df_tickets['satisfaction_score'].fillna(median_score)

In [ ]:
df_tickets['response_category'] = pd.cut(
    df_tickets['first_response_time_minutes'],
    bins=[0, 30, 60, 120, 180],
    labels=['fast', 'moderate', 'slow', 'very slow']
)

df_tickets.to_csv('ravenstack_support_tickets_cleaned.csv', index=False)

In [ ]:
df_tickets.head(7)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag,response_category
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,4.0,0,slow
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,4.0,0,very slow
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,0,slow
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,0,very slow
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,4.0,0,fast
5,T-90f06d,A-94c3cd,2023-07-27,2023-07-27 09:00:00,9.0,medium,60,4.0,0,moderate
6,T-30b537,A-2e4581,2023-09-09,2023-09-10 03:00:00,27.0,urgent,64,3.0,0,slow

In [ ]:
pip install mysql-connector-python sqlalchemy pymysql

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-macosx_14_0_arm64.whl.metadata (11 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-9.7.0-cp313-cp313-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 22.4 MB/s  0:00:01 eta 0:00:01
Downloading sqlalchemy-2.0.49-cp313-cp313-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 25.1 MB/s  0:00:00
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
Installing collected packages: sqlalchemy, pymysql, mysql-connector-python
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [mysql-connector-python]-connector-python]
Successfully installed mysql-connector-python-9.7.0 pymysql-1.1.3 sqlalchemy-2.0.49

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:123456@localhost:3306/raven_analytics')

In [ ]:
pip install cryptography

Requirement already satisfied: cryptography in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (48.0.0)
Requirement already satisfied: cffi>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography) (3.0)

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
df.to_sql('accounts', con=engine, if_exists='replace', index=False)
df_churn.to_sql('churn_events', con=engine, if_exists='replace', index=False)
df_subs.to_sql('subscriptions', con=engine, if_exists='replace', index=False)
df_usage.to_sql('feature_usage', con=engine, if_exists='replace', index=False)
df_tickets.to_sql('support_tickets', con=engine, if_exists='replace', index=False)

print('All tables loaded successfully')

RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

In [ ]:
import sys
!{sys.executable} -m pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (9.7.0)

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine

engine = create_engine(
    'mysql+mysqlconnector://root:123456@localhost:3306/ravenstack_analytics'
)

In [ ]:
df.to_sql('accounts', con=engine, if_exists='replace', index=False)
df_churn.to_sql('churn_events', con=engine, if_exists='replace', index=False)
df_subs.to_sql('subscriptions', con=engine, if_exists='replace', index=False)
df_usage.to_sql('feature_usage', con=engine, if_exists='replace', index=False)
df_tickets.to_sql('support_tickets', con=engine, if_exists='replace', index=False)

print('All tables loaded successfully')

ProgrammingError: (mysql.connector.errors.ProgrammingError) 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
(Background on this error at: https://sqlalche.me/e/20/f405)

NameError: name 'df_churn' is not defined

In [10]:
import pandas as pd

df_churn = pd.read_csv('/Users/prachisharma/Desktop/Desktop Files/PythonRoadmap/Python coding/cleaned-churn_events.csv')
df_churn.head(10)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive
5,C-a8ac26,A-b20d99,2024-03-04,features,0.00,False,False,False,missing features
6,C-2e2966,A-526d93,2024-07-10,features,34.40,True,False,False,NaN
7,C-ee531b,A-751bd4,2024-09-22,budget,0.00,False,False,False,NaN
8,C-e6a0f0,A-ccabf0,2024-10-31,features,0.00,False,False,False,too expensive
9,C-9328ba,A-0a62f5,2024-10-10,features,0.00,False,False,False,switched to competitor

In [11]:
df_churn.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    str
 1   account_id                600 non-null    str
 2   churn_date                600 non-null    str
 3   reason_code               600 non-null    str
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    str
dtypes: bool(3), float64(1), str(5)
memory usage: 30.0 KB

In [12]:
df_churn['preceding_upgrade_flag'] = df_churn['preceding_upgrade_flag'].astype(int)
df_churn['preceding_downgrade_flag'] = df_churn['preceding_downgrade_flag'].astype(int)
df_churn['is_reactivation'] = df_churn['is_reactivation'].astype(int)

In [13]:
df_churn.head(10)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,0,0,0,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,1,0,0,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,0,0,0,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,0,0,0,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,0,1,1,too expensive
5,C-a8ac26,A-b20d99,2024-03-04,features,0.00,0,0,0,missing features
6,C-2e2966,A-526d93,2024-07-10,features,34.40,1,0,0,NaN
7,C-ee531b,A-751bd4,2024-09-22,budget,0.00,0,0,0,NaN
8,C-e6a0f0,A-ccabf0,2024-10-31,features,0.00,0,0,0,too expensive
9,C-9328ba,A-0a62f5,2024-10-10,features,0.00,0,0,0,switched to competitor

In [14]:
df_churn.to_csv('cleaned-churn_events.csv', index=False)

In [15]:
import pandas as pd

df = pd.read_csv('/Users/prachisharma/Desktop/Desktop Files/PythonRoadmap/Python coding/ravenstack_accounts_cleaned.csv')
df.head(10)

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,account_tenure_days
0,A-2e4581,Company_0,edtech,US,2024-10-16,partner,Basic,9,0,0,575
1,A-43a9e3,Company_1,fintech,IN,2023-08-17,other,Basic,18,0,1,1001
2,A-0a282f,Company_2,devtools,US,2024-08-27,organic,Basic,1,0,0,625
3,A-1f0ac7,Company_3,healthtech,UK,2023-08-27,other,Basic,24,1,0,991
4,A-ce550d,Company_4,healthtech,US,2024-10-27,event,Enterprise,35,0,1,564
5,A-1b9609,Company_5,edtech,IN,2023-10-12,ads,Enterprise,4,0,0,945
6,A-a0ca4e,Company_6,cybersecurity,US,2024-03-08,ads,Pro,11,0,0,797
7,A-e5d6ab,Company_7,edtech,US,2023-04-15,partner,Pro,3,0,0,1125
8,A-7dacce,Company_8,cybersecurity,CA,2024-09-10,event,Enterprise,12,0,1,611
9,A-10b8da,Company_9,devtools,US,2023-05-08,partner,Enterprise,14,0,1,1102

In [16]:
import pandas as pd

df_usage = pd.read_csv('/Users/prachisharma/Desktop/Desktop Files/PythonRoadmap/Python coding/ravenstack_feature_usage_cleaned.csv')
df_usage.head(10)

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature,usage_duration_mins,is_zero_usage
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,0,83.40,0
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,0,6.15,0
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,0,24.30,0
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,0,34.75,0
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,0,15.00,0
5,U-c5692d,S-e958ba,2023-10-31,feature_14,11,4103,0,0,68.38,0
6,U-7078db,S-0c9fdd,2023-09-20,feature_34,8,2016,2,0,33.60,0
7,U-a60033,S-4e4ab7,2023-06-05,feature_27,10,5470,0,0,91.17,0
8,U-5cd930,S-a3a1c1,2024-02-20,feature_18,9,5067,1,0,84.45,0
9,U-ebb375,S-9e450b,2023-02-09,feature_28,6,2778,0,0,46.30,0

In [17]:
import pandas as pd

df_subs = pd.read_csv('/Users/prachisharma/Desktop/Desktop Files/PythonRoadmap/Python coding/ravenstack_subscriptions_cleaned.csv')
df_subs.head(10)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaN,enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaN,enterprise,27,5373,64476,False,False,False,False,monthly,True
5,S-4b9b13,A-fa2041,2024-08-13,NaN,pro,15,735,8820,False,False,False,False,monthly,True
6,S-dceac6,A-417d2f,2023-12-30,NaN,enterprise,4,796,9552,False,False,False,False,annual,True
7,S-8cad7b,A-5f2961,2024-12-23,NaN,basic,16,304,3648,False,False,False,False,annual,True
8,S-24796e,A-cc8c8f,2024-11-27,NaN,enterprise,23,4577,54924,False,False,False,False,annual,False
9,S-d0c344,A-80eeb6,2024-10-27,NaN,pro,22,1078,12936,False,False,False,False,annual,False

In [18]:
df_subs['is_trial'] = df_subs['is_trial'].astype(int)

In [19]:
df_subs.head(10)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,enterprise,14,2786,33432,0,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,pro,17,833,9996,0,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaN,enterprise,62,0,0,1,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,enterprise,5,995,11940,0,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaN,enterprise,27,5373,64476,0,False,False,False,monthly,True
5,S-4b9b13,A-fa2041,2024-08-13,NaN,pro,15,735,8820,0,False,False,False,monthly,True
6,S-dceac6,A-417d2f,2023-12-30,NaN,enterprise,4,796,9552,0,False,False,False,annual,True
7,S-8cad7b,A-5f2961,2024-12-23,NaN,basic,16,304,3648,0,False,False,False,annual,True
8,S-24796e,A-cc8c8f,2024-11-27,NaN,enterprise,23,4577,54924,0,False,False,False,annual,False
9,S-d0c344,A-80eeb6,2024-10-27,NaN,pro,22,1078,12936,0,False,False,False,annual,False

In [20]:
df_subs['upgrade_flag'] = df_subs['upgrade_flag'].astype(int)
df_subs['downgrade_flag'] = df_subs['downgrade_flag'].astype(int)
df_subs['churn_flag'] = df_subs['churn_flag'].astype(int)
df_subs['auto_renew_flag'] = df_subs['auto_renew_flag'].astype(int)

In [21]:
df_subs.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    5000 non-null   str
 1   account_id         5000 non-null   str
 2   start_date         5000 non-null   str
 3   end_date           486 non-null    str
 4   plan_tier          5000 non-null   str
 5   seats              5000 non-null   int64
 6   mrr_amount         5000 non-null   int64
 7   arr_amount         5000 non-null   int64
 8   is_trial           5000 non-null   int64
 9   upgrade_flag       5000 non-null   int64
 10  downgrade_flag     5000 non-null   int64
 11  churn_flag         5000 non-null   int64
 12  billing_frequency  5000 non-null   str
 13  auto_renew_flag    5000 non-null   int64
dtypes: int64(8), str(6)
memory usage: 547.0 KB

In [22]:
df_subs['subscription_duration_days'] = (
    df_subs['end_date'] - df_subs['start_date']
).dt.days

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [23]:
start = pd.to_datetime(df_subs['start_date'])
end = pd.to_datetime(df_subs['end_date'])

# Step 2: subtract and extract days
df_subs['subscription_duration_days'] = (end - start).dt.days

In [24]:
df_subs.head(10)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag,subscription_duration_days
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,enterprise,14,2786,33432,0,0,0,1,monthly,1,111.0
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,pro,17,833,9996,0,0,0,0,monthly,1,NaN
2,S-51c0d1,A-659280,2024-11-25,NaN,enterprise,62,0,0,1,1,0,0,annual,0,NaN
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,enterprise,5,995,11940,0,0,0,1,monthly,1,20.0
4,S-cff5a2,A-ba6516,2024-01-10,NaN,enterprise,27,5373,64476,0,0,0,0,monthly,1,NaN
5,S-4b9b13,A-fa2041,2024-08-13,NaN,pro,15,735,8820,0,0,0,0,monthly,1,NaN
6,S-dceac6,A-417d2f,2023-12-30,NaN,enterprise,4,796,9552,0,0,0,0,annual,1,NaN
7,S-8cad7b,A-5f2961,2024-12-23,NaN,basic,16,304,3648,0,0,0,0,annual,1,NaN
8,S-24796e,A-cc8c8f,2024-11-27,NaN,enterprise,23,4577,54924,0,0,0,0,annual,0,NaN
9,S-d0c344,A-80eeb6,2024-10-27,NaN,pro,22,1078,12936,0,0,0,0,annual,0,NaN

In [25]:
df_subs['subscription_duration_days'] = df_subs['subscription_duration_days'].astype('Int64')

In [26]:
df_subs.head(10)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag,subscription_duration_days
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,enterprise,14,2786,33432,0,0,0,1,monthly,1,111
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,pro,17,833,9996,0,0,0,0,monthly,1,<NA>
2,S-51c0d1,A-659280,2024-11-25,NaN,enterprise,62,0,0,1,1,0,0,annual,0,<NA>
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,enterprise,5,995,11940,0,0,0,1,monthly,1,20
4,S-cff5a2,A-ba6516,2024-01-10,NaN,enterprise,27,5373,64476,0,0,0,0,monthly,1,<NA>
5,S-4b9b13,A-fa2041,2024-08-13,NaN,pro,15,735,8820,0,0,0,0,monthly,1,<NA>
6,S-dceac6,A-417d2f,2023-12-30,NaN,enterprise,4,796,9552,0,0,0,0,annual,1,<NA>
7,S-8cad7b,A-5f2961,2024-12-23,NaN,basic,16,304,3648,0,0,0,0,annual,1,<NA>
8,S-24796e,A-cc8c8f,2024-11-27,NaN,enterprise,23,4577,54924,0,0,0,0,annual,0,<NA>
9,S-d0c344,A-80eeb6,2024-10-27,NaN,pro,22,1078,12936,0,0,0,0,annual,0,<NA>

In [27]:
df_subs.to_csv('ravenstack_subscriptions_cleaned.csv', index=False)

In [28]:
import pandas as pd

df_tickets = pd.read_csv('/Users/prachisharma/Desktop/Desktop Files/PythonRoadmap/Python coding/ravenstack_support_tickets_cleaned.csv')
df_tickets.head(10)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag,response_category
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,4.0,0,slow
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,4.0,0,very slow
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,0,slow
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,0,very slow
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,4.0,0,fast
5,T-90f06d,A-94c3cd,2023-07-27,2023-07-27 09:00:00,9.0,medium,60,4.0,0,moderate
6,T-30b537,A-2e4581,2023-09-09,2023-09-10 03:00:00,27.0,urgent,64,3.0,0,slow
7,T-60242d,A-72799b,2024-01-29,2024-01-29 12:00:00,12.0,low,56,4.0,1,moderate
8,T-7119c9,A-b179bf,2023-08-27,2023-08-27 16:00:00,16.0,urgent,154,4.0,0,very slow
9,T-b0edf2,A-7cfe77,2024-05-06,2024-05-07 04:00:00,28.0,medium,150,3.0,0,very slow

In [29]:
import pandas as pd

df_subs = pd.read_csv('/Users/prachisharma/Desktop/Desktop Files/PythonRoadmap/Python coding/ravenstack_subscriptions_cleaned.csv')
df_subs.head(10)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag,subscription_duration_days
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,enterprise,14,2786,33432,0,0,0,1,monthly,1,111.0
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,pro,17,833,9996,0,0,0,0,monthly,1,NaN
2,S-51c0d1,A-659280,2024-11-25,NaN,enterprise,62,0,0,1,1,0,0,annual,0,NaN
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,enterprise,5,995,11940,0,0,0,1,monthly,1,20.0
4,S-cff5a2,A-ba6516,2024-01-10,NaN,enterprise,27,5373,64476,0,0,0,0,monthly,1,NaN
5,S-4b9b13,A-fa2041,2024-08-13,NaN,pro,15,735,8820,0,0,0,0,monthly,1,NaN
6,S-dceac6,A-417d2f,2023-12-30,NaN,enterprise,4,796,9552,0,0,0,0,annual,1,NaN
7,S-8cad7b,A-5f2961,2024-12-23,NaN,basic,16,304,3648,0,0,0,0,annual,1,NaN
8,S-24796e,A-cc8c8f,2024-11-27,NaN,enterprise,23,4577,54924,0,0,0,0,annual,0,NaN
9,S-d0c344,A-80eeb6,2024-10-27,NaN,pro,22,1078,12936,0,0,0,0,annual,0,NaN

In [30]:
df_subs['subscription_duration_days'] = df_subs['subscription_duration_days'].astype('Int64')

In [31]:
df_subs.head(10)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag,subscription_duration_days
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,enterprise,14,2786,33432,0,0,0,1,monthly,1,111
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,pro,17,833,9996,0,0,0,0,monthly,1,<NA>
2,S-51c0d1,A-659280,2024-11-25,NaN,enterprise,62,0,0,1,1,0,0,annual,0,<NA>
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,enterprise,5,995,11940,0,0,0,1,monthly,1,20
4,S-cff5a2,A-ba6516,2024-01-10,NaN,enterprise,27,5373,64476,0,0,0,0,monthly,1,<NA>
5,S-4b9b13,A-fa2041,2024-08-13,NaN,pro,15,735,8820,0,0,0,0,monthly,1,<NA>
6,S-dceac6,A-417d2f,2023-12-30,NaN,enterprise,4,796,9552,0,0,0,0,annual,1,<NA>
7,S-8cad7b,A-5f2961,2024-12-23,NaN,basic,16,304,3648,0,0,0,0,annual,1,<NA>
8,S-24796e,A-cc8c8f,2024-11-27,NaN,enterprise,23,4577,54924,0,0,0,0,annual,0,<NA>
9,S-d0c344,A-80eeb6,2024-10-27,NaN,pro,22,1078,12936,0,0,0,0,annual,0,<NA>

In [32]:
df_subs.to_csv('ravenstack_subscriptions_cleaned.csv', index=False)

In [33]:
df_subs.head(10)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag,subscription_duration_days
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,enterprise,14,2786,33432,0,0,0,1,monthly,1,111
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,pro,17,833,9996,0,0,0,0,monthly,1,<NA>
2,S-51c0d1,A-659280,2024-11-25,NaN,enterprise,62,0,0,1,1,0,0,annual,0,<NA>
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,enterprise,5,995,11940,0,0,0,1,monthly,1,20
4,S-cff5a2,A-ba6516,2024-01-10,NaN,enterprise,27,5373,64476,0,0,0,0,monthly,1,<NA>
5,S-4b9b13,A-fa2041,2024-08-13,NaN,pro,15,735,8820,0,0,0,0,monthly,1,<NA>
6,S-dceac6,A-417d2f,2023-12-30,NaN,enterprise,4,796,9552,0,0,0,0,annual,1,<NA>
7,S-8cad7b,A-5f2961,2024-12-23,NaN,basic,16,304,3648,0,0,0,0,annual,1,<NA>
8,S-24796e,A-cc8c8f,2024-11-27,NaN,enterprise,23,4577,54924,0,0,0,0,annual,0,<NA>
9,S-d0c344,A-80eeb6,2024-10-27,NaN,pro,22,1078,12936,0,0,0,0,annual,0,<NA>

In [1]:
import pandas as pd

df_usage = pd.read_csv('ravenstack_feature_usage_cleaned.csv')
df_usage.duplicated().sum()

np.int64(0)

In [4]:
df_usage[df_usage['usage_id'].duplicated()].shape

(21, 10)